---
# tasks file for apigee-opdk-setup-java-home
- name: Validate that java_home is available
  fail:
    msg: "Please provide java_home"
  when: java_home is not defined

- name: Remove old JAVA_HOME
  lineinfile:
    create: yes
    dest: "{{ apigee_installation_home }}/etc/defaults.sh"
    regexp: "{{ item }}"
    state: absent
    backup: yes
  with_items:
  - "^JAVA_HOME="
  - "^export JAVA_HOME"
  - "^PATH=$JAVA_HOME/bin:$PATH"

- name: Update environment with JAVA_HOME
  lineinfile:
    create: yes
    dest: "{{ apigee_installation_home }}/etc/defaults.sh"
    regexp: "{{ item.regexp }}"
    line: '{{ item.line }}'
    backup: yes
  with_items:
  - { regexp: "^JAVA_HOME=", line: "JAVA_HOME={{ java_home }}" }
  - { regexp: "^PATH=$JAVA_HOME/bin:$PATH", line: "^PATH=$JAVA_HOME/bin:$PATH"}
  - { regexp: "^export JAVA_HOME", line: "^export JAVA_HOME"}


- name: Update environment with path JAVA_HOME
  lineinfile:
    dest: "{{ apigee_installation_home }}/etc/defaults.sh"
    line: 'PATH=$JAVA_HOME/bin:$PATH'
    backup: yes
